# Generated by Django 5.0.2 on 2024-02-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='todo_name',
        ),
    ]
